spring.application.name=trendy-threads

spring.datasource.url=jdbc:mysql://localhost:3306/trendy_threads
spring.datasource.username=root
spring.datasource.password=Salamon@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never



